@host=http://localhost:3000

GET {{host}} http/1.1

### Register
POST {{host}}/user/register http/1.1
Content-Type: application/json

{
    "email": "user3@gmail.com",
    "password": "user3"
}

### Login
POST {{host}}/user/login http/1.1
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "user1"
}

### Login
POST {{host}}/user/login http/1.1
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "password": "user2"
}

### Login Without Todos
POST {{host}}/user/login http/1.1
Content-Type: application/json

{
    "email": "user3@gmail.com",
    "password": "user3"
}

### All todos
GET {{host}}/todo
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjI0NTUwOTI0fQ.DtlFuSCC6wurNOAQF0txsAAlIC7YEALo3Ybv9ucUk_k

### Certain todo
GET {{host}}/todo/1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjI0NTUyMTIxfQ.5K0u2-Y3irxzZgeXqgneaLbqQ1o5sSlvy7iJB4hpCh8

### Create todo
POST {{host}}/todo
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjI0NTUyMTIxfQ.5K0u2-Y3irxzZgeXqgneaLbqQ1o5sSlvy7iJB4hpCh8

{
    "title": "Watch Demon Slayer",
    "description": "Watch Demon Slayer in Netflix",
    "status": "to execute",
    "due_date": "2021-06-29 00:00:00"
}

### Patch todo
PATCH {{host}}/todo/3
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjI0NTUzMjM3fQ.UPWhL2EILsj2ZO11JHM6ECUu6gupvlj-qQZaB-r3KKM

{
    "due_date": ""
}

### Patch unauthorized todo
PATCH {{host}}/todo/5
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI0NTUzMDkwfQ.agilj5IduA7F2Ezh1sO6fjt0c3AM7GdcwHGvIbaGdT4

{
    "due_date": "2021-05-31 00:00:00"
}

### Put todo
PUT {{host}}/todo/1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI0NTUzNjI4fQ.uYbyTwGtDXbawzdbKRS4srvLo-wgLMvSc-yCOIuNi-Q

{
    "title": "adfasdf",
    "description": "asdfasdfasdfasdf",
    "status": "to plan",
    "due_date": "2021-06-30 00:00:00"
}

### Put todo
DELETE {{host}}/todo/1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI0NTU0MjY0fQ.hh7uryGHWM2AMLta6giNUUPAgRHiPTwcGDijTVuSIDE